version: '3'
services:
  app:
    build: .
    command: pipenv run server
    volumes:
      - .:/app:cached
    ports:
      - 5000:5000
#     depends_on:
#       - db
#       - selenium
#   db:
#     image: postgres:11.1-alpine
#     volumes:
#       - db:/var/lib/postgresql/data
#   selenium:
#     image: selenium/standalone-chrome-debug
#     ports:
#       - 4444:4444
#       - 5900:5900
# volumes:
#   db:
#     driver: local
